destination: production
markdown: redcarpet
paginate: 10
highlighter: pygments
sass:
  sass_dir: _sass
gems: [jekyll-paginate]

blog_site_url: https://blog.bazel.build
docs_site_url: https://docs.bazel.build
